# -*- coding: utf-8 -*-
"""Modelagem conta de energia

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14eQuCFa80AupDVXmuYzoVM4V832fegGG
"""

# • Entrada dada pelos usuarios: consumo em kWh e a bandeira vigente.
# • Saída do programa: ’O seu consumo foi de ... reais e voce tera um desconto
# de ... na sua fatura.’

#Declaração de variáveis	
consumoKwh = 0
bandeiraVigente = str
tarifa = 0.81256
bandeiraAmarela = 0.01874
consumoReais = 0
desconto = int

# descontoFatura = 0
#bandeiraVerde = 0

#Coletando dados dos usuário 
consumoKwh = int(input("Insira o seu consumo em kWh desse mês "))
bandeiraVigente = str(input("Informe a bandeira vigente \n Informe V para verde e A para amarela "))
bandeiraVigente = bandeiraVigente.upper()

#Função do calculo do consumoKwh, coonsumo em reais e
#Verifificação da bandeira selecionada
#bandeira verde
if bandeiraVigente == 'V':
    #f(x) = consumoKwh*tarifa
    consumoReais = int(consumoKwh*tarifa)
if bandeiraVigente == 'A':
    #f(x) = consumoKwh * (tarifa+bandeiraAmarela)
    consumoReais = consumoKwh*(tarifa+bandeiraAmarela)

#calculo do desconto que será dado em cima do consumo em reais
# Função
# f(x)= 
  # 65% se x <= 30
  # 40% se 30 > x <= 100 
  # 10% se  100 >  x <= 220 
  # 0% se x > 200

consumo = consumoReais
#Estrutura condicional para verificar o desconto do cliente
if consumo <= 30:
    #f(consumo) = (40*consumo)/100
      desconto = (40*consumo)/100
    #   print("Deu 65% de desconto, você terá "+ str(desconto) + " reais de desconto") 
if consumo > 30 and consumo <= 100:
      desconto = (40*consumo)/100
    #   print("Deu 40% de desconto, você terá "+ str(desconto) + " reais de desconto")
if consumo > 100 and consumo <= 220:
      desconto = (10*consumo)/100
    #   print("Deu 10% de desconto, você terá "+ str(desconto) + " reais de; desconto")
if consumo > 220:
      desconto = (0*consumo)/100
    #   print("Deu 0% de desconto, você terá "+ str(desconto) + " reais de desconto")


#valor com desconto aplicado
valorTotal = consumo-desconto

#Resposta do programa
print("O seu consumo foi de R$ %.2f" %(consumoReais), "e você terá um desconto de R$ %.2f" %(desconto), "na sua fatura. O valor total a ser pago será de R$ %.2f" %valorTotal)